// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Pervasives = require("bs-platform/lib/js/pervasives.js");

var $$float = 1.1 + 1.2;

var bool = Pervasives.bool_of_string("true");

var and_ = Pervasives.bool_of_string("true") && true;

console.log("endlne");

console.log("Vienna");

var home = "Warsaw";

console.log(home);

var sum = 2;

var smaller = true;

var bigger = true;

exports.sum = sum;
exports.$$float = $$float;
exports.smaller = smaller;
exports.bigger = bigger;
exports.bool = bool;
exports.and_ = and_;
exports.home = home;
/* bool Not a pure module */
