// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Pervasives = require("bs-platform/lib/js/pervasives.js");

var $$float = 1.1 + 1.2;

var bool = Pervasives.bool_of_string("true");

var and_ = Pervasives.bool_of_string("true") && true;

var or_ = Pervasives.bool_of_string("false") && false;

var print = Pervasives.print_int(44);

console.log(2);

console.log($$float);

console.log(true);

console.log(true);

console.log(bool);

console.log(and_);

console.log(or_);

console.log(print);

var sum = 2;

var smaller = true;

var bigger = true;

exports.sum = sum;
exports.$$float = $$float;
exports.smaller = smaller;
exports.bigger = bigger;
exports.bool = bool;
exports.and_ = and_;
exports.or_ = or_;
exports.print = print;
/* bool Not a pure module */
